### ISSUE TITLE
Why not just add pull requests to the main app?

### ISSUE THREAD

**Issue by CodeCubeNeo** [stephanritscher/Simple-Contacts#14] opened 2023-07-30 14:15 UTC
Did the tibbi developer of original simple contacts pro (from simple mobile tools) reject them?

**Comment by shuvashish76** [comment] 2023-07-30 19:00
Duplicate of #6

**Comment by stephanritscher** [comment] 2023-08-13 20:58
Unfortunately yes, at least for the structured address feature.

**Closed by stephanritscher** 2023-08-13 20:58 UTC
